name: Artifact Actions for Num-Codex

on: push

jobs:

  build-docker-images:
    runs-on: ubuntu-latest
    steps:
    - name: Check out Git repository
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Build with Maven
      run: mvn -B verify --file pom.xml

    - name: Login to GitHub Docker Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push BPE image
      uses: docker/build-push-action@v2
      with:
        context: dsf-bpe/dsf-bpe-server-jetty/docker
        tags: ghcr.io/num-codex/highmed-dsf/bpe:${{ github.sha }}
        push: true


    - name: Build and push FHIR image
      uses: docker/build-push-action@v2
      with:
        context: dsf-fhir/dsf-fhir-server-jetty/docker
        tags: ghcr.io/num-codex/highmed-dsf/fhir:${{ github.sha }}
        push: true
